# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Shared/gnostr.org/gnostr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Shared/gnostr.org/gnostr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Shared/gnostr.org/gnostr/CMakeFiles /Users/Shared/gnostr.org/gnostr//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Shared/gnostr.org/gnostr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nostr

# Build rule for target.
nostr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nostr
.PHONY : nostr

# fast build rule for target.
nostr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/build
.PHONY : nostr/fast

#=============================================================================
# Target rules for targets named http_client

# Build rule for target.
http_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_client
.PHONY : http_client

# fast build rule for target.
http_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/build
.PHONY : http_client/fast

#=============================================================================
# Target rules for targets named http_relay

# Build rule for target.
http_relay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http_relay
.PHONY : http_relay

# fast build rule for target.
http_relay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/build
.PHONY : http_relay/fast

#=============================================================================
# Target rules for targets named gnostr-client

# Build rule for target.
gnostr-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gnostr-client
.PHONY : gnostr-client

# fast build rule for target.
gnostr-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-client.dir/build.make CMakeFiles/gnostr-client.dir/build
.PHONY : gnostr-client/fast

#=============================================================================
# Target rules for targets named gnostr-req

# Build rule for target.
gnostr-req: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gnostr-req
.PHONY : gnostr-req

# fast build rule for target.
gnostr-req/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-req.dir/build.make CMakeFiles/gnostr-req.dir/build
.PHONY : gnostr-req/fast

#=============================================================================
# Target rules for targets named gnostr-gnode

# Build rule for target.
gnostr-gnode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gnostr-gnode
.PHONY : gnostr-gnode

# fast build rule for target.
gnostr-gnode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-gnode.dir/build.make CMakeFiles/gnostr-gnode.dir/build
.PHONY : gnostr-gnode/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named secp256k1_precomputed

# Build rule for target.
secp256k1_precomputed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1_precomputed
.PHONY : secp256k1_precomputed

# fast build rule for target.
secp256k1_precomputed/fast:
	$(MAKE) $(MAKESILENT) -f ext/secp256k1-0.3.2/src/CMakeFiles/secp256k1_precomputed.dir/build.make ext/secp256k1-0.3.2/src/CMakeFiles/secp256k1_precomputed.dir/build
.PHONY : secp256k1_precomputed/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f ext/secp256k1-0.3.2/src/CMakeFiles/secp256k1.dir/build.make ext/secp256k1-0.3.2/src/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

#=============================================================================
# Target rules for targets named nostri

# Build rule for target.
nostri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nostri
.PHONY : nostri

# fast build rule for target.
nostri/fast:
	$(MAKE) $(MAKESILENT) -f src/nostril/CMakeFiles/nostri.dir/build.make src/nostril/CMakeFiles/nostri.dir/build
.PHONY : nostri/fast

#=============================================================================
# Target rules for targets named configurator

# Build rule for target.
configurator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 configurator
.PHONY : configurator

# fast build rule for target.
configurator/fast:
	$(MAKE) $(MAKESILENT) -f src/nostril/CMakeFiles/configurator.dir/build.make src/nostril/CMakeFiles/configurator.dir/build
.PHONY : configurator/fast

#=============================================================================
# Target rules for targets named nostril

# Build rule for target.
nostril: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nostril
.PHONY : nostril

# fast build rule for target.
nostril/fast:
	$(MAKE) $(MAKESILENT) -f src/nostril/CMakeFiles/nostril.dir/build.make src/nostril/CMakeFiles/nostril.dir/build
.PHONY : nostril/fast

src/database.o: src/database.cc.o
.PHONY : src/database.o

# target to build an object file
src/database.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/database.cc.o
.PHONY : src/database.cc.o

src/database.i: src/database.cc.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/database.cc.i
.PHONY : src/database.cc.i

src/database.s: src/database.cc.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/database.cc.s
.PHONY : src/database.cc.s

src/http/http.o: src/http/http.cc.o
.PHONY : src/http/http.o

# target to build an object file
src/http/http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http.cc.o
.PHONY : src/http/http.cc.o

src/http/http.i: src/http/http.cc.i
.PHONY : src/http/http.i

# target to preprocess a source file
src/http/http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http.cc.i
.PHONY : src/http/http.cc.i

src/http/http.s: src/http/http.cc.s
.PHONY : src/http/http.s

# target to generate assembly for a file
src/http/http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http.cc.s
.PHONY : src/http/http.cc.s

src/http/http_client.o: src/http/http_client.cc.o
.PHONY : src/http/http_client.o

# target to build an object file
src/http/http_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http_client.cc.o
.PHONY : src/http/http_client.cc.o

src/http/http_client.i: src/http/http_client.cc.i
.PHONY : src/http/http_client.i

# target to preprocess a source file
src/http/http_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http_client.cc.i
.PHONY : src/http/http_client.cc.i

src/http/http_client.s: src/http/http_client.cc.s
.PHONY : src/http/http_client.s

# target to generate assembly for a file
src/http/http_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/src/http/http_client.cc.s
.PHONY : src/http/http_client.cc.s

src/http/http_relay.o: src/http/http_relay.cc.o
.PHONY : src/http/http_relay.o

# target to build an object file
src/http/http_relay.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http_relay.cc.o
.PHONY : src/http/http_relay.cc.o

src/http/http_relay.i: src/http/http_relay.cc.i
.PHONY : src/http/http_relay.i

# target to preprocess a source file
src/http/http_relay.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http_relay.cc.i
.PHONY : src/http/http_relay.cc.i

src/http/http_relay.s: src/http/http_relay.cc.s
.PHONY : src/http/http_relay.s

# target to generate assembly for a file
src/http/http_relay.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http_relay.dir/build.make CMakeFiles/http_relay.dir/src/http/http_relay.cc.s
.PHONY : src/http/http_relay.cc.s

src/log.o: src/log.cc.o
.PHONY : src/log.o

# target to build an object file
src/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/log.cc.o
.PHONY : src/log.cc.o

src/log.i: src/log.cc.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/log.cc.i
.PHONY : src/log.cc.i

src/log.s: src/log.cc.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/log.cc.s
.PHONY : src/log.cc.s

src/nostr.o: src/nostr.cc.o
.PHONY : src/nostr.o

# target to build an object file
src/nostr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/nostr.cc.o
.PHONY : src/nostr.cc.o

src/nostr.i: src/nostr.cc.i
.PHONY : src/nostr.i

# target to preprocess a source file
src/nostr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/nostr.cc.i
.PHONY : src/nostr.cc.i

src/nostr.s: src/nostr.cc.s
.PHONY : src/nostr.s

# target to generate assembly for a file
src/nostr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/nostr.cc.s
.PHONY : src/nostr.cc.s

src/relay.o: src/relay.cc.o
.PHONY : src/relay.o

# target to build an object file
src/relay.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/relay.cc.o
.PHONY : src/relay.cc.o

src/relay.i: src/relay.cc.i
.PHONY : src/relay.i

# target to preprocess a source file
src/relay.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/relay.cc.i
.PHONY : src/relay.cc.i

src/relay.s: src/relay.cc.s
.PHONY : src/relay.s

# target to generate assembly for a file
src/relay.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/relay.cc.s
.PHONY : src/relay.cc.s

src/uuid.o: src/uuid.cc.o
.PHONY : src/uuid.o

# target to build an object file
src/uuid.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/uuid.cc.o
.PHONY : src/uuid.cc.o

src/uuid.i: src/uuid.cc.i
.PHONY : src/uuid.i

# target to preprocess a source file
src/uuid.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/uuid.cc.i
.PHONY : src/uuid.cc.i

src/uuid.s: src/uuid.cc.s
.PHONY : src/uuid.s

# target to generate assembly for a file
src/uuid.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostr.dir/build.make CMakeFiles/nostr.dir/src/uuid.cc.s
.PHONY : src/uuid.cc.s

src/wss_client.o: src/wss_client.cc.o
.PHONY : src/wss_client.o

# target to build an object file
src/wss_client.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-client.dir/build.make CMakeFiles/gnostr-client.dir/src/wss_client.cc.o
.PHONY : src/wss_client.cc.o

src/wss_client.i: src/wss_client.cc.i
.PHONY : src/wss_client.i

# target to preprocess a source file
src/wss_client.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-client.dir/build.make CMakeFiles/gnostr-client.dir/src/wss_client.cc.i
.PHONY : src/wss_client.cc.i

src/wss_client.s: src/wss_client.cc.s
.PHONY : src/wss_client.s

# target to generate assembly for a file
src/wss_client.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-client.dir/build.make CMakeFiles/gnostr-client.dir/src/wss_client.cc.s
.PHONY : src/wss_client.cc.s

src/wss_relay.o: src/wss_relay.cc.o
.PHONY : src/wss_relay.o

# target to build an object file
src/wss_relay.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-gnode.dir/build.make CMakeFiles/gnostr-gnode.dir/src/wss_relay.cc.o
.PHONY : src/wss_relay.cc.o

src/wss_relay.i: src/wss_relay.cc.i
.PHONY : src/wss_relay.i

# target to preprocess a source file
src/wss_relay.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-gnode.dir/build.make CMakeFiles/gnostr-gnode.dir/src/wss_relay.cc.i
.PHONY : src/wss_relay.cc.i

src/wss_relay.s: src/wss_relay.cc.s
.PHONY : src/wss_relay.s

# target to generate assembly for a file
src/wss_relay.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-gnode.dir/build.make CMakeFiles/gnostr-gnode.dir/src/wss_relay.cc.s
.PHONY : src/wss_relay.cc.s

src/wss_req.o: src/wss_req.cc.o
.PHONY : src/wss_req.o

# target to build an object file
src/wss_req.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-req.dir/build.make CMakeFiles/gnostr-req.dir/src/wss_req.cc.o
.PHONY : src/wss_req.cc.o

src/wss_req.i: src/wss_req.cc.i
.PHONY : src/wss_req.i

# target to preprocess a source file
src/wss_req.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-req.dir/build.make CMakeFiles/gnostr-req.dir/src/wss_req.cc.i
.PHONY : src/wss_req.cc.i

src/wss_req.s: src/wss_req.cc.s
.PHONY : src/wss_req.s

# target to generate assembly for a file
src/wss_req.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gnostr-req.dir/build.make CMakeFiles/gnostr-req.dir/src/wss_req.cc.s
.PHONY : src/wss_req.cc.s

test/tests.o: test/tests.cc.o
.PHONY : test/tests.o

# target to build an object file
test/tests.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tests.cc.o
.PHONY : test/tests.cc.o

test/tests.i: test/tests.cc.i
.PHONY : test/tests.i

# target to preprocess a source file
test/tests.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tests.cc.i
.PHONY : test/tests.cc.i

test/tests.s: test/tests.cc.s
.PHONY : test/tests.s

# target to generate assembly for a file
test/tests.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/tests.cc.s
.PHONY : test/tests.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... configurator"
	@echo "... gnostr-client"
	@echo "... gnostr-gnode"
	@echo "... gnostr-req"
	@echo "... http_client"
	@echo "... http_relay"
	@echo "... nostr"
	@echo "... nostri"
	@echo "... nostril"
	@echo "... secp256k1"
	@echo "... secp256k1_precomputed"
	@echo "... tests"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/http/http.o"
	@echo "... src/http/http.i"
	@echo "... src/http/http.s"
	@echo "... src/http/http_client.o"
	@echo "... src/http/http_client.i"
	@echo "... src/http/http_client.s"
	@echo "... src/http/http_relay.o"
	@echo "... src/http/http_relay.i"
	@echo "... src/http/http_relay.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/nostr.o"
	@echo "... src/nostr.i"
	@echo "... src/nostr.s"
	@echo "... src/relay.o"
	@echo "... src/relay.i"
	@echo "... src/relay.s"
	@echo "... src/uuid.o"
	@echo "... src/uuid.i"
	@echo "... src/uuid.s"
	@echo "... src/wss_client.o"
	@echo "... src/wss_client.i"
	@echo "... src/wss_client.s"
	@echo "... src/wss_relay.o"
	@echo "... src/wss_relay.i"
	@echo "... src/wss_relay.s"
	@echo "... src/wss_req.o"
	@echo "... src/wss_req.i"
	@echo "... src/wss_req.s"
	@echo "... test/tests.o"
	@echo "... test/tests.i"
	@echo "... test/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

