name: macos-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos-build_and_test:
    strategy:
      matrix:
        os: [macos-latest, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ ! env.ACT }}
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: printenv
        run: |
          printenv
      - name: make
        run: |
          type -P brew && brew install automake || echo "install automake"
          make submodules
          make all
      - name: make install
        run: |
          sudo -S make install
      - name: man gnostr
        run: |
          type -P gnostr && man gnostr || echo "man gnostr not working..."
      - name: gnostr
        run: |
          #pipe handles non-zero return from gnostr default help
          sudo make install > /dev/null 2>&1
          type -P gnostr && gnostr --envelope -t gnostr --content ""
