name: ubuntu-gnostr-sha256

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        if: ${{ !env.ACT }}
        with:
          access_token: ${{ github.token }}
      - name: Restore deps
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            libsecp256k1.a
            /root/.cargo
            /root/.rustup
            CARGO_TARGET_DIR
          key: ${{ runner.os }}-deps

      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'
          submodules: 'true'
          set-safe-directory: 'true'

      - uses: actions-rs/toolchain@v1.0.6
        #if: ${{ !env.ACT }}
        with:
          toolchain: stable

      - name: apt-get install
        #if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake bash build-essential gettext libcurl4-openssl-dev libtool make python3 python3-pip util-linux zlib1g-dev cmake g++ cargo

      - run: touch ~/GITHUB_TOKEN.txt

      - run: sudo make detect
      - run: sudo cmake .

      - run: make gnostr-sha256 && which gnostr-sha256

      - name: Save deps
        id: cache-deps-save
        uses: actions/cache/save@v3
        if: ${{ !env.ACT }}
        with:
          path: |
            libsecp256k1.a
            /root/.cargo
            /root/.rustup
            CARGO_TARGET_DIR
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

